# General settings
general = {}

# Generation settings
[generation_settings]
	# The size of nether biome regions from each mod that uses TerraBlender.
	# Range: 2-6
	# Punto medio entre tamaño y diversidad.
	nether_region_size = 4
	# The size of overworld biome regions from each mod that uses TerraBlender.
	# Range: 2-6
	# Mantiene una mezcla razonable.
	overworld_region_size = 4
	# The weighting of vanilla biome regions in the nether.
	# Range: 0-2147483647
	# Equilibrio entre vanilla y mods.
	vanilla_nether_region_weight = 10
	# The weighting of vanilla biome regions in the overworld.
	# Range: 0-2147483647
	# Igual proporción entre vanilla y mods.
	vanilla_overworld_region_weight = 10

